// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhBuxXNWc0aAqPuSwaU5arnNdG9tYNWQ',
    appId: '1:396831624:web:c0a10e2cf8f847c50aa83d',
    messagingSenderId: '396831624',
    projectId: 'chat-app-4ef99',
    authDomain: 'chat-app-4ef99.firebaseapp.com',
    storageBucket: 'chat-app-4ef99.firebasestorage.app',
    measurementId: 'G-9RJSKFPDMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrmiNj8h_wXop3sO3heuE_UY1Or7ztAQ',
    appId: '1:396831624:android:aebb62d7aebb1e3e0aa83d',
    messagingSenderId: '396831624',
    projectId: 'chat-app-4ef99',
    storageBucket: 'chat-app-4ef99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvozlUuV2NLFYZHYNjzMfvQogK1vTd-Hc',
    appId: '1:396831624:ios:c0a296228dd226df0aa83d',
    messagingSenderId: '396831624',
    projectId: 'chat-app-4ef99',
    storageBucket: 'chat-app-4ef99.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvozlUuV2NLFYZHYNjzMfvQogK1vTd-Hc',
    appId: '1:396831624:ios:c0a296228dd226df0aa83d',
    messagingSenderId: '396831624',
    projectId: 'chat-app-4ef99',
    storageBucket: 'chat-app-4ef99.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGhBuxXNWc0aAqPuSwaU5arnNdG9tYNWQ',
    appId: '1:396831624:web:aa03404fd81ca8b00aa83d',
    messagingSenderId: '396831624',
    projectId: 'chat-app-4ef99',
    authDomain: 'chat-app-4ef99.firebaseapp.com',
    storageBucket: 'chat-app-4ef99.firebasestorage.app',
    measurementId: 'G-8LMYLZP1WX',
  );
}
